### ISSUE TITLE
parallel builds

### ISSUE THREAD

**Issue by jfromaniello** [Strider-CD/strider-docker-runner#19]
can this runner be used to achieve parallel builds?

**Comment by nomean42** [comment]
Looks like this is not still solved? ((

**Comment by thedewpoint** [comment]
@nomean42  not sure if you solved this but looks like you can set an environment variable to override the concurrent build settings: 
https://github.com/Strider-CD/strider-simple-runner/blob/master/lib/index.js#L62  
   concurrentJobs: parseInt(process.env.CONCURRENT_JOBS || '1', 10) || 1,

**Comment by knownasilya** [comment]
Yes this also applies to the simple-runner, and is documented in the main Strider repo.
