### ISSUE TITLE
Syntax error from stdout of running container

### ISSUE THREAD

**Issue by davemackintosh** [Strider-CD/strider-docker-runner#26]
I get the following error when I try to use this plugin to run a locally created docker image (built by `strider-docker-build`)

```
17 Dec 18:52:20 - info: [runner:docker] Queued new job. Project: project/test Job ID: 5491d0e38d6c3e120c00000d
17 Dec 18:52:20 - info: [runner:docker] Job started. Project: 17 Dec 18:52:20 - info: [runner:docker] Queued new job. Project: project/test Job ID: 5491d0e38d6c3e120c00000d
17 Dec 18:52:20 - info: [runner:docker] Job started. Project: project/test Job ID: 5491d0e38d6c3e120c00000d
GET /stylesheets/css/plugin-status-compiled.css 304 61ms
17 Dec 18:52:20 - info: Git Version:1.7
GET /javascripts/pages/plugin-status-compiled.js 304 63ms
17 Dec 18:52:24 - info: Job 5491d0e38d6c3e120c00000d  bitbucket gitane command done %s; exit code %s; duration %s git clone --recursive git@bitbucket.com:project/test . -b master 0 3721
17 Dec 18:52:24 - error: [SyntaxError: Unexpected token s] 'attemping to parse:' 'server running on 8080' Job ID: 5491d0e38d6c3e120c00000d
GET /stylesheets/css/plugin-status-compiled.css 304 61ms
17 Dec 18:52:20 - info: Git Version:1.7
GET /javascripts/pages/plugin-status-compiled.js 304 63ms
17 Dec 18:52:24 - info: Job 5491d0e38d6c3e120c00000d  bitbucket gitane command done %s; exit code %s; duration %s git clone --recursive git@bitbucket.com:project/test . -b master 0 3721
17 Dec 18:52:24 - error: [SyntaxError: Unexpected token s] 'attemping to parse:' 'server running on 8080'
```

**Comment by knownasilya** [comment]
Looks like it would be easier to convert the data to a valid JSON object.

**Comment by knownasilya** [comment]
How do you setup the runner with docker-build? Trying to recreate the scenario.

**Comment by knownasilya** [comment]
Ping @davemackintosh

**Comment by davemackintosh** [comment]
The PR was closed quite rightly in the `event-stream` repo, the issue is not receiving JSON from the stdout so a format needs creating that takes stdout and transforms it into a message that can be parsed as JSON.

I don't have any time this week to investigate but I will try to have a gander next week if that's okay with everyone?

**Comment by davemackintosh** [comment]
Also, using docker build is what triggered me to update the docker runner plugin to choose the point at which the runner actually runs the image. I'll recreate in the next few days and post some instructions here as it's all a bit hazey for me right now haha.

**Comment by knownasilya** [comment]
How have you fared @davemackintosh?

**Comment by davemackintosh** [comment]
Really sorry, I've had a hectic week with baby and work. I will look into this over the weekend :)

Dave Mackintosh
CEO
https://newworld.codes
@newworldcode
+447742627143<tel:+447742627143>
The information contained in this e-mail is confidential and may be privileged. It is intended for the addressee only. If you are not the intended recipient, please delete this e-mail immediately and advise the sender accordingly. The contents of this e-mail must not be disclosed or copied without the sender's consent.

New World Code Ltd is a limited business in England and Wales, Company number 09161562<tel:09161562>

On 24 Jun 2015, at 22:21, Ilya Radchenko <notifications@github.com<mailto:notifications@github.com>> wrote:


How have you fared @davemackintosh<https://github.com/davemackintosh>?

-
