### ISSUE TITLE
secure tcp/https connections to remote docker hosts

### ISSUE THREAD

**Issue by patrickjahns** [Strider-CD/strider-docker-runner#31]
Right now it seems that connections are not secured. Docker offers tls for tcp/https connections. We just need to enable it by providing certificates on the server and client.

I`ve seen that [docker-optionator](https://github.com/keyvanfatehi/dockerode-optionator) already provides a function for easy loading of certifiactes. 

Not sure though what is the best approach for storing the certificates (on filesystem? in the database?)

**Comment by knownasilya** [comment]
@patrickjahns filesystem certs should work already, as long as you have the correct env variable set. This is a docker thing, not so much strider.

**Comment by patrickjahns** [comment]
Thank you for the answer - for now using one cert would be great. What environment variable needs to be set and where? Is there a way to eventually put this in a configuration file or document it in a more obvious way?

**Comment by knownasilya** [comment]
`DOCKER_CERT_PATH` is what you want I think. I'm not sure, but you might be able to use the 'env' plugin, otherwise just set it on your system.

**Comment by patrickjahns** [comment]
I can not specify certifiactes individually but a path? Do I need to inhere any naming conventions other then the one docker uses?

**Comment by knownasilya** [comment]
@patrickjahns I think it's all docker specific.

**Comment by patrickjahns** [comment]
Allright thanks - I check the Docker documentaiton on it a bit more closely - for anyone else looking for information have a look at 
http://docs.docker.com/articles/https/

Will try it again

**Comment by patrickjahns** [comment]
It is working for me, thank you

**Comment by knownasilya** [comment]
@patrickjahns could you submit a PR for the README, on how to set the cert? Would be much appreciated.
