### ISSUE TITLE
docker version

### ISSUE THREAD

**Issue by abusquets** [Strider-CD/strider-docker-runner#43]
Hi,

when i try to test a project with docker runner I have this error

Error: (HTTP code 400) unexpected - starting container with non-empty request body was deprecated since v1.10 and removed in v1.12
I think this is due to my docker version, any recomendation in order to solve this? thanks

**Comment by knownasilya** [comment]
What's your version of docker?

**Comment by abusquets** [comment]
Server Version: 17.06.0-ce

**Comment by abusquets** [comment]
Server Version: 17.06.0-ce

**Comment by abusquets** [comment]
@knownasilya 
Sorry I resolved with

cd node_modules
rm -rf strider-docker-runner
git clone https://github.com/Strider-CD/strider-docker-runner.git
cd strider-docker-runner
npm install

Thanks

**Comment by knownasilya** [comment]
That can be done in the plugins menu, just update the version of the plugin there.
