### ISSUE TITLE
Bug when the image's name contains a colon

### ISSUE THREAD

**Issue by xgalen** [Strider-CD/strider-docker-runner#44]
Because this line: https://github.com/Strider-CD/strider-docker-runner/blob/8857bf4cdf369ae9616104b6c0206a56e4fbec66/lib/create-container.js#L12

If the name is something like `aaaaa:bbbb:latest` it does not work. It happened to me.

I don't know if it's better to fix the code, put something in the docs or just don't nothing. Now I know the problem I know how to avoid it (changing the name).

**Comment by knownasilya** [comment]
Probably fix the code, and only use the last segment, but rejoin the rest.

**Comment by xgalen** [comment]
Solved with PR #46

**Comment by knownasilya** [comment]
Tip: In PRs you can say 'fixes #issuenumber' or resolves, etc and it will automatically close the issue when the PR is merged.
