### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by xgalen** [Strider-CD/strider-docker-runner#45]
Hi all,

There are a lot of commits done by @oliversalzburg but since there is not a new `release` they are not being updated on `strider` in production. I know how to launch a new release but not sure if do it or it's better @knownasilya or @oliversalzburg to do so.

**Comment by knownasilya** [comment]
Feel free to have at it 👍

**Comment by xgalen** [comment]
@knownasilya I'm doing something wrong and the `release` it's not taking the latest commit with the version upgrade. Maybe it's because the tests are not passing due to `Greenkeeper`?

Sorry, I have never done this before :(

**Comment by knownasilya** [comment]
You need to update the plugin record at https://github.com/Strider-CD/ecosystem-index/blob/master/plugins.yml to the new version.

**Comment by xgalen** [comment]
Thanks. Also it seems like the `release` does not catch the latest commit with the version upgrade, because it says there is a new commit into master. I have tried to `delete` and re-do the release but still the same result.

**Comment by knownasilya** [comment]
Yeah releases are somewhat finicky. Next time make sure you are on the master branch before creating the release, that should help.

**Comment by xgalen** [comment]
Sorry but it still does not work. Now it appears on the Strider's plugin list but does not upgrade the plugin. I think the reason it's the `release` does not contain actually the commit with the upgrade in the `package.json`.  I have tried removing and adding again, but GitHub seems to not recognize that commit :'(
